FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD redbus2.jar /opt/redbus2/
EXPOSE 8080
WORKDIR /opt/redbus2/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "redbus2.jar"]
