FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD project.jar /opt/project/
EXPOSE 8080
WORKDIR /opt/project/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "project.jar"]
