FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD amazon2.jar /opt/amazon2/
EXPOSE 8080
WORKDIR /opt/amazon2/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "amazon2.jar"]
